import os
from anthropic import Anthropic
from pydantic_settings import BaseSettings

class AISettings(BaseSettings):
    anthropic_api_key: str = os.getenv("ANTHROPIC_API_KEY", "")
    model_name: str = "claude-3-5-sonnet-20240620"

settings = AISettings()
client = Anthropic(api_key=settings.anthropic_api_key)

async def call_claude(prompt: str, system_prompt: str = ""):
    """Standardized wrapper for Claude API calls (Requirement 50.1-50.4)"""
    if not settings.anthropic_api_key:
        return "MOCK AI RESPONSE (API KEY MISSING): This would be generated by Claude-3.5-Sonnet."
    
    response = client.messages.create(
        model=settings.model_name,
        max_tokens=1024,
        system=system_prompt,
        messages=[{"role": "user", "content": prompt}]
    )
    return response.content[0].text
