-- ─────────────────────────────────────────────────────────────
-- 030 — Email Designer: Brand Settings, Templates, Sends, Campaigns
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS email_brand_settings (
    id                  BIGSERIAL PRIMARY KEY,
    tenant_id           UUID NOT NULL,
    company_code        VARCHAR(2) NOT NULL,
    company_name_en     VARCHAR(200),
    company_name_ar     VARCHAR(200),
    logo_url            TEXT,
    logo_dark_url       TEXT,
    color_primary       VARCHAR(7) DEFAULT '#1E3A5F',
    color_secondary     VARCHAR(7) DEFAULT '#2E86C1',
    color_accent        VARCHAR(7) DEFAULT '#F39C12',
    color_bg            VARCHAR(7) DEFAULT '#F8F9FA',
    color_text          VARCHAR(7) DEFAULT '#2C3E50',
    color_text_muted    VARCHAR(7) DEFAULT '#7F8C8D',
    color_button        VARCHAR(7) DEFAULT '#1E3A5F',
    color_button_text   VARCHAR(7) DEFAULT '#FFFFFF',
    color_footer_bg     VARCHAR(7) DEFAULT '#2C3E50',
    color_footer_text   VARCHAR(7) DEFAULT '#ECF0F1',
    font_family         VARCHAR(100) DEFAULT 'Inter, Arial, sans-serif',
    font_size_base      INT DEFAULT 16,
    font_size_heading   INT DEFAULT 24,
    font_size_small     INT DEFAULT 13,
    sender_name_en      VARCHAR(200),
    sender_name_ar      VARCHAR(200),
    sender_email        VARCHAR(200),
    reply_to_email      VARCHAR(200),
    sender_phone        VARCHAR(30),
    sender_address_en   TEXT,
    sender_address_ar   TEXT,
    website_url         VARCHAR(500),
    footer_html_en      TEXT,
    footer_html_ar      TEXT,
    footer_social_links JSONB,
    header_html         TEXT,
    smtp_host           VARCHAR(200),
    smtp_port           INT DEFAULT 587,
    smtp_username       VARCHAR(200),
    smtp_password_enc   TEXT,
    smtp_encryption     VARCHAR(10) DEFAULT 'tls',
    smtp_provider       VARCHAR(30) DEFAULT 'smtp',
    api_key_enc         TEXT,
    api_domain          VARCHAR(200),
    email_width         INT DEFAULT 600,
    border_radius       INT DEFAULT 8,
    unsubscribe_page    TEXT,
    physical_address    TEXT,
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW(),
    UNIQUE(tenant_id, company_code)
);

CREATE TABLE IF NOT EXISTS email_templates (
    id                  BIGSERIAL PRIMARY KEY,
    tenant_id           UUID NOT NULL,
    company_code        VARCHAR(2),
    name                VARCHAR(300) NOT NULL,
    name_ar             VARCHAR(300),
    description         TEXT,
    category            VARCHAR(50) NOT NULL DEFAULT 'custom',
    subject_en          TEXT,
    subject_ar          TEXT,
    preheader_en        VARCHAR(500),
    preheader_ar        VARCHAR(500),
    json_design         JSONB NOT NULL DEFAULT '{}',
    mjml_source         TEXT,
    html_compiled       TEXT,
    html_compiled_at    TIMESTAMP,
    language            VARCHAR(5) DEFAULT 'ar',
    is_rtl              BOOLEAN DEFAULT TRUE,
    is_active           BOOLEAN DEFAULT TRUE,
    is_system           BOOLEAN DEFAULT FALSE,
    is_locked           BOOLEAN DEFAULT FALSE,
    apply_brand         BOOLEAN DEFAULT TRUE,
    brand_override      JSONB,
    merge_fields_used   JSONB,
    send_count          INT DEFAULT 0,
    open_rate           DECIMAL(5,2),
    click_rate          DECIMAL(5,2),
    last_used_at        TIMESTAMP,
    created_by          VARCHAR(20),
    updated_by          VARCHAR(20),
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW(),
    deleted_at          TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tmpl_tenant_cat ON email_templates(tenant_id, category);
CREATE INDEX IF NOT EXISTS idx_tmpl_company    ON email_templates(tenant_id, company_code);
CREATE INDEX IF NOT EXISTS idx_tmpl_active     ON email_templates(is_active) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS email_campaigns (
    id                  BIGSERIAL PRIMARY KEY,
    tenant_id           UUID NOT NULL,
    company_code        VARCHAR(2) NOT NULL,
    template_id         BIGINT REFERENCES email_templates(id),
    name                VARCHAR(300) NOT NULL,
    description         TEXT,
    status              VARCHAR(20) DEFAULT 'draft'
                        CHECK (status IN ('draft','scheduled','sending','sent','cancelled')),
    audience_type       VARCHAR(20),
    audience_filter     JSONB,
    recipient_count     INT,
    scheduled_at        TIMESTAMP,
    started_at          TIMESTAMP,
    completed_at        TIMESTAMP,
    total_sent          INT DEFAULT 0,
    total_delivered     INT DEFAULT 0,
    total_opened        INT DEFAULT 0,
    total_clicked       INT DEFAULT 0,
    total_bounced       INT DEFAULT 0,
    total_unsubscribed  INT DEFAULT 0,
    created_by          VARCHAR(20),
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS email_sends (
    id                  BIGSERIAL PRIMARY KEY,
    tenant_id           UUID NOT NULL,
    company_code        VARCHAR(2) NOT NULL,
    template_id         BIGINT REFERENCES email_templates(id),
    campaign_id         BIGINT REFERENCES email_campaigns(id),
    contact_id          BIGINT,
    deal_id             BIGINT,
    invoice_id          BIGINT,
    triggered_by        VARCHAR(50),
    from_name           VARCHAR(200),
    from_email          VARCHAR(200),
    reply_to            VARCHAR(200),
    to_email            VARCHAR(200) NOT NULL,
    to_name             VARCHAR(200),
    subject             TEXT NOT NULL,
    preheader           VARCHAR(500),
    html_body           TEXT NOT NULL,
    text_body           TEXT,
    attachments         JSONB,
    provider            VARCHAR(30),
    message_id          VARCHAR(300),
    provider_response   JSONB,
    status              VARCHAR(20) NOT NULL DEFAULT 'queued',
    queued_at           TIMESTAMP DEFAULT NOW(),
    sent_at             TIMESTAMP,
    delivered_at        TIMESTAMP,
    first_opened_at     TIMESTAMP,
    last_opened_at      TIMESTAMP,
    open_count          INT DEFAULT 0,
    first_clicked_at    TIMESTAMP,
    click_count         INT DEFAULT 0,
    bounced_at          TIMESTAMP,
    bounce_type         VARCHAR(20),
    bounce_reason       TEXT,
    spam_reported_at    TIMESTAMP,
    unsubscribed_at     TIMESTAMP,
    failed_at           TIMESTAMP,
    fail_reason         TEXT,
    retry_count         INT DEFAULT 0,
    merge_context       JSONB,
    created_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sends_tenant_status ON email_sends(tenant_id, status, sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_sends_contact       ON email_sends(contact_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_sends_campaign      ON email_sends(campaign_id);
CREATE INDEX IF NOT EXISTS idx_sends_message_id    ON email_sends(message_id);

CREATE TABLE IF NOT EXISTS email_click_events (
    id              BIGSERIAL PRIMARY KEY,
    send_id         BIGINT REFERENCES email_sends(id),
    tenant_id       UUID NOT NULL,
    contact_id      BIGINT,
    url_original    TEXT NOT NULL,
    url_tracking    TEXT,
    click_count     INT DEFAULT 0,
    first_clicked   TIMESTAMP,
    last_clicked    TIMESTAMP,
    ip_address      INET,
    user_agent      TEXT,
    device_type     VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS email_unsubscribes (
    id              BIGSERIAL PRIMARY KEY,
    tenant_id       UUID NOT NULL,
    company_code    VARCHAR(2),
    email           VARCHAR(300) NOT NULL,
    contact_id      BIGINT,
    reason          TEXT,
    unsubscribed_at TIMESTAMP DEFAULT NOW(),
    ip_address      INET,
    UNIQUE(tenant_id, email)
);
