apiVersion: v2
name: nexsaas
description: A Helm chart for NexSaaS Modular CRM
type: application
version: 1.0.0
appVersion: "1.24.0"
dependencies:
  - name: postgresql
    version: 15.2.5
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 18.0.0
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 12.0.0
    repository: https://charts.bitnami.com/bitnami
